FROM python:latest 

RUN pip install flask 

COPY ./static /home/imageweb_app/static/ 
COPY ./templates /home/imageweb_app/templates/ 
COPY ./flask_app.py /home/imageweb_app/ 

EXPOSE 5050 

CMD python /home/imageweb_app/flask_app.py